### ISSUE TITLE
Noto Sans Arabic isn't working on Word, is glitched on PowerPoint, but works on Excel

### ISSUE THREAD

**Issue by GarfQC** [notofonts/arabic#197] opened 2023-08-10 22:31 UTC
Note that I'm trying to use the static fonts.

On Word, when I chose Noto Sans Arabic, it defaults to Arial. And when I try to change the font to Noto Sans Arabic, it stays to Arial.
![image](https://github.com/notofonts/arabic/assets/89820063/bce93431-d214-453a-b63a-8701bd003726)

On PowerPoint, the font is glitched!
![image](https://github.com/notofonts/arabic/assets/89820063/6f7f039d-fba3-4961-b0e9-7cbfb38ce243)
Text meant to be shown here: أوه لا ، الخط معطل!

On Excel though, it seems to work fine.
![image](https://github.com/notofonts/arabic/assets/89820063/9c16d139-44a9-47ea-a339-0e96d4bf6283)

**Comment by simoncozens** [comment] 2023-08-11 06:20
I think this is a duplicate of #28. (And probably a Windows issue rather than a font issue, but I'm less sure about that.) Let's continue to track it over there.

**Closed by simoncozens** 2023-08-11 06:20 UTC
