### ISSUE TITLE
Arabic: what’s missing from Unicode 13

### ISSUE THREAD

**Issue by Mercury13** [notofonts/arabic#30] opened 2021-09-20 19:23 UTC
Again, Unicode 14 is out! And I’m checking your newest Arabic font (NotoNaskhArabic-Regular.ttf, this repo, downloaded today, v2.012) against U13.

08A1 Arabic letter Beh with hamza above
08AD Arabic letter Low Alef
08AE Arabic letter Dal with three dots below
08AF Arabic letter Sad with three dots below
08B0 Arabic letter Gaf with inverted stroke
08B2 Arabic letter Zain with inverted V above
08B3 Arabic letter Ain with three dots below
08B4 Arabic letter Kaf with dot below
08B6 Arabic letter Beh with small Meem above
08B7 Arabic letter Peh with small Meem above
08B8 Arabic letter Teh with small Teh above
08B9 Arabic letter Reh with small Noon above
08BA Arabic letter Yeh with two dots below and small Noon above
08BB Arabic letter African Feh
08BC Arabic letter African Qaf
08BD Arabic letter African Noon
08BE Arabic letter Peh with small V
08BF Arabic letter Teh with small V
08C0 Arabic letter Tteh with small V
08C1 Arabic letter Tcheh with small V
08C2 Arabic letter Keheh with small V
08C3 Arabic letter Ghain with three dots above
08C4 Arabic letter African Qaf with three dots above
08C5 Arabic letter Jeem with three dots above
08C6 Arabic letter Jeem with three dots below
08C7 Arabic letter Lam with small Arabic letter Tah above
08D3 Arabic small low Waw
08D4 Arabic small high word Ar-rub
08D5 Arabic small high Sad
08D6 Arabic small high Ain
08D7 Arabic small high Qaf
08D8 Arabic small high Noon with kasra
08D9 Arabic small low Noon with kasra
08DA Arabic small high word Ath-thalatha
08DB Arabic small high word As-sajda
08DC Arabic small high word An-nisf
08DD Arabic small high word Sakta
08DE Arabic small high word Qif
08DF Arabic small high word Waqfa
08E0 Arabic small high footnote marker
08E1 Arabic small high sign Safha
08E2 Arabic disputed end of ayah
08E3 Arabic turned damma below
08FF Arabic mark Sideways Noon ghunna

~Arabic Mathematical Alphabetic Symbols (the entire block)~ (Sorry, mistaken, implemented in Math)

Thank you.

**Comment by simoncozens** [comment] 2023-01-24 14:54
1) I'm working on it!
2) This is a duplicate of #15!

**Closed by simoncozens** 2023-01-24 14:54 UTC
Labels: Script-Arabic, Naskh, Type-Enhancement
